<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="W0_GRID.aspx.cs" Inherits="CRUD_withGridView_SQLDataSource.W0_GRID" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            margin-left: 385px;
        }
    </style>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div>
        <!-- This are bound field ie. this are binded w/database ie. we cannot change them -->
        <!-- by Edit Columns in grid view select columns and choose change to template fields to do so-->
        <!-- Also we are adding custom Footer template and linkButton inside it to insert new data -->
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="Id" DataSourceID="SqlDataSource1" ShowFooter="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
            <Columns>
                <asp:TemplateField HeaderText="Id" SortExpression="Id">
                    <EditItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("Id") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label6" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:LinkButton ID="LinkButton1" ValidationGroup="insertGroup" runat="server" OnClick="LinkButton1_Click">Insert</asp:LinkButton>
                    </FooterTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="rollno" SortExpression="rollno">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("rollno") %>'></asp:TextBox>
                        <asp:RequiredFieldValidator ControlToValidate="TextBox1" Text="*" ForeColor="#FF0066"  Font-Size="Larger" SetFocusOnError="true" ID="RequiredFieldValidator1" runat="server" ErrorMessage="Rollno is required"></asp:RequiredFieldValidator>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("rollno") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="FooterRollTextbox" runat="server"></asp:TextBox>
                        <asp:RequiredFieldValidator ControlToValidate="FooterRollTextbox" ValidationGroup="insertGroup" Text="*" ForeColor="#FF0066"  Font-Size="Larger" SetFocusOnError="true" ID="RequiredFieldValidator2" runat="server" ErrorMessage="Rollno is required"></asp:RequiredFieldValidator>
                    </FooterTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="name" SortExpression="name">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("name") %>'></asp:TextBox>
                        <asp:RequiredFieldValidator ControlToValidate="TextBox2" Text="*" ForeColor="#FF0066"  Font-Size="Larger" SetFocusOnError="true" ID="RequiredFieldValidator3" runat="server" ErrorMessage="Name is required"></asp:RequiredFieldValidator>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="FooterNameTextbox" runat="server"></asp:TextBox>
                        <asp:RequiredFieldValidator ControlToValidate="FooterNameTextbox" ValidationGroup="insertGroup" Text="*" ForeColor="#FF0066"  Font-Size="Larger" SetFocusOnError="true" ID="RequiredFieldValidator4" runat="server" ErrorMessage="Name is required"></asp:RequiredFieldValidator>
                    </FooterTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="gender" SortExpression="gender">
                    <EditItemTemplate>
                        <asp:DropDownList ID="GenderDropDown2" runat="server" Text='<%# Bind("gender") %>'>
                            <asp:ListItem>Male</asp:ListItem>
                            <asp:ListItem>Female</asp:ListItem>
                            <asp:ListItem>Other</asp:ListItem>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("gender") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:DropDownList ID="GenderDropDown1" runat="server">
                            <asp:ListItem Selected="True">Male</asp:ListItem>
                            <asp:ListItem>Female</asp:ListItem>
                            <asp:ListItem>Other</asp:ListItem>
                        </asp:DropDownList>
                    </FooterTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="class" SortExpression="class">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("class") %>'></asp:TextBox>
                        <asp:RequiredFieldValidator ControlToValidate="TextBox4" Text="*" Display="Dynamic" ForeColor="#FF0066"  Font-Size="Larger" SetFocusOnError="true" ID="RequiredFieldValidator5" runat="server" ErrorMessage="Class is required"></asp:RequiredFieldValidator>
                        <asp:RangeValidator ControlToValidate="TextBox4" Type="Integer" Display="Dynamic" Text="*" ForeColor="#FF0066"  Font-Size="Larger" SetFocusOnError="true" MinimumValue="1" MaximumValue="12" ID="RangeValidator1" runat="server" ErrorMessage="RangeValidator"></asp:RangeValidator>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("class") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="FooterClassTextbox" runat="server"></asp:TextBox>
                        <asp:RequiredFieldValidator ControlToValidate="FooterClassTextbox" ValidationGroup="insertGroup" Text="*" Display="Dynamic" ForeColor="#FF0066"  Font-Size="Larger" SetFocusOnError="true" ID="RequiredFieldValidator6" runat="server" ErrorMessage="Class is required"></asp:RequiredFieldValidator>
                        <asp:RangeValidator ControlToValidate="FooterClassTextbox" ValidationGroup="insertGroup" Type="Integer" Text="*" Display="Dynamic" ForeColor="#FF0066"  Font-Size="Larger" SetFocusOnError="true" MinimumValue="1" MaximumValue="12" ID="RangeValidator2" runat="server" ErrorMessage="RangeValidator"></asp:RangeValidator>
                    </FooterTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="div" SortExpression="div">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DivDropDown2" runat="server" Text='<%# Bind("div") %>'>
                            <asp:ListItem>A</asp:ListItem>
                            <asp:ListItem>B</asp:ListItem>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label5" runat="server" Text='<%# Bind("div") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:DropDownList ID="DivDropDown1" runat="server">
                            <asp:ListItem Selected="True">A</asp:ListItem>
                            <asp:ListItem>B</asp:ListItem>
                        </asp:DropDownList>
                    </FooterTemplate>
                </asp:TemplateField>
            </Columns>
            <FooterStyle BackColor="White" ForeColor="#000066" />
            <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
            <RowStyle ForeColor="#000066" />
            <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#007DBB" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#00547E" />
        </asp:GridView>
        <br />
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [student] WHERE [Id] = @Id" InsertCommand="INSERT INTO [student] ([rollno], [name], [gender], [class], [div]) VALUES (@rollno, @name, @gender, @class, @div)" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [student]" UpdateCommand="UPDATE [student] SET [rollno] = @rollno, [name] = @name, [gender] = @gender, [class] = @class, [div] = @div WHERE [Id] = @Id">
            <DeleteParameters>
                <asp:Parameter Name="Id" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Id" Type="Int32" />
                <asp:Parameter Name="rollno" Type="Int32" />
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="gender" Type="String" />
                <asp:Parameter Name="class" Type="Int32" />
                <asp:Parameter Name="div" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="rollno" Type="Int32" />
                <asp:Parameter Name="name" Type="String" />
                <asp:Parameter Name="gender" Type="String" />
                <asp:Parameter Name="class" Type="Int32" />
                <asp:Parameter Name="div" Type="String" />
                <asp:Parameter Name="Id" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <div>
        <br />
        </div>
    </div>
</asp:Content>
